
export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST'
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS'
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL'
export const DOWNLOAD_FILE_RESET = 'DOWNLOAD_FILE_RESET'

export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL'
export const DELETE_FILE_RESET = 'DELETE_FILE_RESET'