export const FINE_CREATE_REQUEST = 'FINE_CREATE_REQUEST'
export const FINE_CREATE_SUCCESS = 'FINE_CREATE_SUCCESS'
export const FINE_CREATE_FAIL = 'FINE_CREATE_FAIL'


export const FINE_UPDATE_REQUEST = 'FINE_UPDATE_REQUEST'
export const FINE_UPDATE_SUCCESS = 'FINE_UPDATE_SUCCESS'
export const FINE_UPDATE_FAIL = 'FINE_UPDATE_FAIL'
export const FINE_UPDATE_RESET = 'FINE_UPDATE_RESET'


// export const FINE_DETAILS_USER_REQUEST = 'FINE_DETAILS_USER_REQUEST'
// export const FINE_DETAILS_USER_SUCCESS = 'FINE_DETAILS_USER_SUCCESS'
// export const FINE_DETAILS_USER_FAIL = 'FINE_DETAILS_USER_FAIL'
// export const FINE_DETAILS_USER_RESET = 'FINE_DETAILS_USER_RESET'


export const FINE_DELETE_REQUEST = 'FINE_DELETE_REQUEST'
export const FINE_DELETE_SUCCESS = 'FINE_DELETE_SUCCESS '
export const FINE_DELETE_FAIL = 'FINE_DELETE_FAIL'


export const FINES_LIST_REQUEST = 'FINES_LIST_REQUEST'
export const FINES_LIST_SUCCESS = 'FINES_LIST_SUCCESS'
export const FINES_LIST_FAIL = 'FINES_LIST_FAIL'
export const FINES_LIST_RESET = 'FINES_LIST_RESET'

export const WRITER_FINES_LIST_REQUEST = 'WRITER_FINES_LIST_REQUEST'
export const WRITER_FINES_LIST_SUCCESS = 'WRITER_FINES_LIST_SUCCESS'
export const WRITER_FINES_LIST_FAIL = 'WRITER_FINES_LIST_FAIL'
export const WRITER_FINES_LIST_RESET = 'WRITER_FINES_LIST_RESET'