export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'


export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'

export const ORDER_EDIT_REQUEST = 'ORDER_EDIT_REQUEST'
export const ORDER_EDIT_SUCCESS = 'ORDER_EDIT_SUCCESS'
export const ORDER_EDIT_FAIL = 'ORDER_EDIT_FAIL'
export const ORDER_EDIT_RESET='ORDER_EDIT_RESET'


export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL='ORDER_DELETE_FAIL'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'
export const  ORDER_LIST_APPEND = 'ORDER_LIST_APPEND'

export const NEW_ORDER_LIST_REQUEST = 'NEW_ORDER_LIST_REQUEST'
export const NEW_ORDER_LIST_SUCCESS = 'NEW_ORDER_LIST_SUCCESS'
export const NEW_ORDER_LIST_FAIL = 'NEW_ORDER_LIST_FAIL'
export const NEW_ORDER_LIST_RESET = 'NEW_ORDER_LIST_RESET'


export const ORDER_CANCEL_REQUEST='ORDER_CANCEL_REQUEST'
export const ORDER_CANCEL_SUCCESS='ORDER_CANCEL_SUCCESS'
export const ORDER_CANCEL_FAIL='ORDER_CANCEL_FAIL'
export const  ORDER_CANCEL_RESET=' ORDER_CANCEL_RESET'
