export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL';
export const PAYMENT_LIST_RESET = 'PAYMENT_LIST_RESET';

export const PAYMENT_DETAILS_REQUEST = 'PAYMENT_DETAILS_REQUEST';
export const PAYMENT_DETAILS_SUCCESS = 'PAYMENT_DETAILS_SUCCESS';
export const PAYMENT_DETAILS_FAIL = 'PAYMENT_DETAILS_FAIL';
export const PAYMENT_DETAILS_RESET = 'PAYMENT_DETAILS_RESET';

export const PAYMENT_CREATE_REQUEST = 'PAYMENT_CREATE_REQUEST';
export const PAYMENT_CREATE_SUCCESS = 'PAYMENT_CREATE_SUCCESS';
export const PAYMENT_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';
export const PAYMENT_CREATE_RESET = 'PAYMENT_CREATE_RESET';

// export const PAYMENT_UPDATE_REQUEST = 'PAYMENT_UPDATE_REQUEST';
// export const PAYMENT_UPDATE_SUCCESS = 'PAYMENT_UPDATE_SUCCESS';
// export const PAYMENT_UPDATE_FAIL = 'PAYMENT_UPDATE_FAIL';

// export const PAYMENT_DELETE_REQUEST = 'PAYMENT_DELETE_REQUEST';
// export const PAYMENT_DELETE_SUCCESS = 'PAYMENT_DELETE_SUCCESS';
// export const PAYMENT_DELETE_FAIL = 'PAYMENT_DELETE_FAIL';
