export const  SUBMISSION_LIST_REQUEST = 'SUBMISSION_LIST_REQUEST'
export const  SUBMISSION_LIST_SUCCESS = 'SUBMISSION_LIST_SUCCESS'
export const  SUBMISSION_LIST_FAIL = 'SUBMISSION_LIST_FAIL'
export const  SUBMISSION_LIST_RESET = 'SUBMISSION_LIST_RESET'


export const SUBMISSION_LIST_REQUEST_BY_FREELANCER = 'SUBMISSION_LIST_REQUEST_BY_FREELANCER'
export const SUBMISSION_LIST_SUCCESS_BY_FREELANCER = 'SUBMISSION_LIST_SUCCESS_BY_FREELANCER'
export const SUBMISSION_LIST_FAIL_BY_FREELANCER = 'SUBMISSION_LIST_FAIL_BY_FREELANCER'
export const SUBMISSION_LIST_RESET_BY_FREELANCER = 'SUBMISSION_LIST_RESET_BY_FREELANCER'

export const DOWNLOAD_SUBMISSION_REQUEST = 'DOWNLOAD_SUBMISSION_REQUEST'
export const DOWNLOAD_SUBMISSION_SUCCESS = 'DOWNLOAD_SUBMISSION_SUCCESS'
export const DOWNLOAD_SUBMISSION_FAIL = 'DOWNLOAD_SUBMISSION_FAIL'
export const DOWNLOAD_SUBMISSION_RESET = 'DOWNLOAD_SUBMISSION_RESET'

export const DELETE_SUBMISSION_REQUEST = 'DELETE_SUBMISSION_REQUEST'
export const DELETE_SUBMISSION_SUCCESS = 'DELETE_SUBMISSION_SUCCESS'
export const DELETE_SUBMISSION_FAIL = 'DELETE_SUBMISSION_FAIL'
export const DELETE_SUBMISSION_RESET = 'DELETE_SUBMISSION_RESET'