export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const FREELANCER_DETAILS_REQUEST = 'FREELANCER_DETAILS_REQUEST'
export const FREELANCER_DETAILS_SUCCESS = 'FREELANCER_DETAILS_SUCCESS'
export const FREELANCER_DETAILS_FAIL = 'FREELANCER_DETAILS_FAIL'
export const FREELANCER_DETAILS_RESET = 'FREELANCER_DETAILS_RESET'


export const MANAGER_DETAILS_REQUEST = 'MANAGER_DETAILS_REQUEST'
export const MANAGER_DETAILS_SUCCESS = 'MANAGER_DETAILS_SUCCESS'
export const MANAGER_DETAILS_FAIL = 'MANAGER_DETAILS_FAIL'
export const MANAGER_DETAILS_RESET = 'MANAGER_DETAILS_RESET'

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'
export const USER_CREATE_RESET = 'USER_CREATE_RESET'


export const FREELANCERS_LIST_REQUEST = 'FREELANCERS_LIST_REQUEST'
export const FREELANCERS_LIST_SUCCESS = 'FREELANCERS_LIST_SUCCESS'
export const FREELANCERS_LIST_FAIL = 'FREELANCERS_LIST_FAIL'
export const FREELANCERS_LIST_RESET = 'FREELANCERS_LIST_RESET'


export const MANAGERS_LIST_REQUEST = 'MANAGERS_LIST_REQUEST'
export const MANAGERS_LIST_SUCCESS = 'MANAGERS_LIST_SUCCESS'
export const MANAGERS_LIST_FAIL = 'MANAGERS_LIST_FAIL'
export const MANAGERS_LIST_RESET = 'MANAGERS_LIST_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'


